# Generated by Django 4.1.5 on 2023-09-14 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebannerimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homebannerimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
