# Generated by Django 4.1.5 on 2023-07-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_homebannerimage_homeproduct_newproduct_topproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeproductimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='newproduct',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='newproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='newproductimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='topproduct',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='topproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='topproductimage',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='home_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='new_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='top_product',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='HomeProduct',
        ),
        migrations.DeleteModel(
            name='HomeProductImage',
        ),
        migrations.DeleteModel(
            name='NewProduct',
        ),
        migrations.DeleteModel(
            name='NewProductImage',
        ),
        migrations.DeleteModel(
            name='TopProduct',
        ),
        migrations.DeleteModel(
            name='TopProductImage',
        ),
    ]
