# Generated by Django 4.1.5 on 2023-07-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_product_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="gender",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.JSONField(null=True),
        ),
    ]
