# Generated by Django 4.1.5 on 2023-08-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_product_color_product_gender_product_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="home_product",
            field=models.BooleanField(default=False),
        ),
    ]
