# Generated by Django 4.1.5 on 2023-08-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_product_home_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="product/"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="color_image",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product/"),
        ),
    ]
