# Generated by Django 4.1.5 on 2023-08-02 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_image_product_color_image_alter_productimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="color",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imagescolor",
                to="product.product",
            ),
        ),
    ]
