# Generated by Django 4.1.5 on 2023-08-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
