# Generated by Django 4.1.5 on 2023-07-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0005_remove_user_address_remove_user_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
