# Generated by Django 4.1.5 on 2023-07-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0006_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
