# Generated by Django 4.1.5 on 2023-07-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0009_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
