# Generated by Django 4.1.5 on 2023-07-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0012_profile_delete_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
