# Generated by Django 4.1.5 on 2023-07-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0013_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_created']},
        ),
    ]
