# Generated by Django 4.1.5 on 2023-07-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authen", "0014_alter_profile_options_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
