# Generated by Django 4.1.5 on 2023-08-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_payment_id',
            field=models.CharField(max_length=255),
        ),
    ]
