# Generated by Django 4.1.5 on 2023-07-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_cancel_order_discount_order_order_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
    ]
