# Generated by Django 4.1.5 on 2023-08-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_payment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='order_payment_id',
            new_name='name',
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_order_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
