# Generated by Django 4.1.5 on 2023-08-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_order_payment_id_payment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='signature_id',
            field=models.CharField(default=4, max_length=255),
            preserve_default=False,
        ),
    ]
