# Generated by Django 4.1.5 on 2023-07-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_city_remove_order_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='user_address',
        ),
    ]
