# Generated by Django 4.1.5 on 2023-07-28 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_rename_address_order_user_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user_address",
        ),
    ]
