# Generated by Django 4.1.5 on 2023-07-28 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_remove_order_user_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="phone",
        ),
        migrations.AddField(
            model_name="order",
            name="user_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="order.address",
            ),
        ),
    ]
