# Generated by Django 4.1.5 on 2023-07-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_remove_order_phone_order_user_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="address_type",
            field=models.CharField(default="home", max_length=255),
        ),
    ]
