# Generated by Django 4.1.5 on 2023-08-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0009_address_default_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="coupon",
            name="number_available",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="coupon",
            name="start_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
