# Generated by Django 4.1.5 on 2023-08-07 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0010_coupon_end_date_coupon_number_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
