# Generated by Django 4.1.5 on 2023-08-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0012_alter_coupon_end_date_alter_coupon_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="start_date",
            field=models.DateTimeField(null=True),
        ),
    ]
