# Generated by Django 4.1.5 on 2023-08-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0013_alter_coupon_end_date_alter_coupon_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="delivered_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="out_for_delivery",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="out_for_delivery_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="returned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
