# Generated by Django 4.1.5 on 2023-08-17 21:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0014_order_delivered_order_delivered_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_data',
        ),
        migrations.AddField(
            model_name='coupon',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='coupon_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
